
export const UPDATE_UNIQUE_ID = 'UPDATE_UNIQUE_ID'; 
export const CURRENT_SEARCH_STRING = 'CURRENT_SEARCH_STRING';
export const RESET_SEARCH = 'RESET_SEARCH'
export const CREATE_SELECTION = 'CREATE_SELECTION'
export const CURRENT_SELECTION = 'CURRENT_SELECTION'