export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INITIALIZE = 'INITIALIZE';
export const UPDATE_UNIQUE_ID = 'UPDATE_UNIQUE_ID'; 